### ISSUE TITLE
System.BadImageFormatException: Bad IL format

### ISSUE THREAD

**Issue by s-nagaev** [anegostudios/VintagestoryServerArm64#8]
Hi! First of all, thank you so much for working on the dedicated server version for the ARM64 platform!

I've built the docker image, and got the following error:
```shell
Unhandled exception. System.BadImageFormatException: Bad IL format. The format of the file '/opt/vintagestory/VintagestoryServer.dl
l' is invalid.
Aborted (core dumped)
```

I haven't made any changes to your Dockerfile. What could be the reason?

**Comment by Th3Dilli** [comment]
this should be fixed now, please try again

so rerun `docker compose up --build`
to force a rebuild
